import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {Search, Button} from 'carbon-components-react'
import {useState} from 'react';
import FavoritesList from './Favorites';

const Home: NextPage = () => {
  const [input, setInput] = useState('')
  const [favorites, setFavorites] = useState([{name: "myfavorite", icon: "Bee"}, {name: "yourFavorite", icon: "Debug"}])
  const onChange = (e: any) => {
    setInput(e.target.value)
  };
  const onClick = () => {
    alert(input)
  }
  return (
    <div className={styles.container}>
     
      <Head>
        <title>IBM Search Engine App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
     
        <h1 className={styles.title}>
          Welcome to IBM Product Search
        </h1>

        <p className={styles.description}>
          Search the entire IBM catelog for the product you need
        </p>
       
        <div className={styles.grid}>
        <Search id="search-1" labelText="Search" onChange={(e)=> onChange(e)}> 
        </Search>
        <Button onClick={()=>onClick()}>Search</Button>
        </div>
        <div className={styles.favorites}>
          <h4>
            Favorites
          </h4>
          <FavoritesList favorites={favorites}></FavoritesList>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Hicham's Squad
        </a>
      </footer>
    </div>
  )
}

export default Home
